# Generated by Django 5.1.7 on 2025-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rates',
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
