# Generated by Django 5.1.7 on 2025-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_currency_rates_currency_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rate',
            new_name='rates',
        ),
    ]
